// Generated by https://quicktype.io
// To parse this JSON data, do
//
//     final poll = pollFromJson(jsonString);

import 'dart:convert';

List<PollModel> pollFromJson(String str) {
  final jsonData = json.decode(str);
  return List<PollModel>.from(jsonData.map((x) => PollModel.fromJson(x)));
}

String pollToJson(List<PollModel> data) {
  final dyn = List<dynamic>.from(data.map((x) => x.toJson()));
  return json.encode(dyn);
}

class PollModel {
  int id;
  final String iri;
  String title;
  String body;
  bool isActive;
  List<PollOptionModel> pollOptions;

  PollModel({
    required this.id,
    required this.iri,
    required this.title,
    required this.body,
    required this.isActive,
    required this.pollOptions,
  });

  factory PollModel.fromJson(Map<String, dynamic> json) => PollModel(
        iri: json["@id"],
        id: json["id"],
        title: json["title"],
        body: json["body"],
        isActive: json["isActive"],
        pollOptions: List<PollOptionModel>.from(
            json["options"].map((x) => PollOptionModel.fromJson(x))),
      );

  Map<String, dynamic> toJson() => {
        "id": id,
        "title": title,
        "body": body,
        "isActive": isActive,
        "options": List<dynamic>.from(pollOptions.map((x) => x.toJson())),
      };
}

class PollOptionModel {
  int id;
  String iri;
  String text;
  bool answered;
  bool selected = false;

  PollOptionModel({
    required this.id,
    required this.iri,
    required this.text,
    required this.answered,
  });

  factory PollOptionModel.fromJson(Map<String, dynamic> json) =>
      PollOptionModel(
        id: json["id"],
        iri: json["@id"],
        text: json["text"],
        answered: json["answered"] == true ? true : false,
      );

  Map<String, dynamic> toJson() => {
        "id": id,
        "text": text,
      };
}
